# Generated by Django 2.2.6 on 2020-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_sentiment',
            field=models.IntegerField(default=-1),
        ),
    ]
